---
- name: provision
  hosts: local
  connection: local
  tasks:

  - name: ensure the keypair is present
    rax_keypair: credentials=~/.rackspace_cloud_credentials
                 name=mykey region=IAD
                 public_key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

  - name: provision the server(s)
    rax: credentials=~/.rackspace_cloud_credentials name=foo
         exact_count=yes count=2 group=only
         image=ubuntu-1204-lts-precise-pangolin
         flavor=performance1-1
         region=IAD
         state=present
         wait=yes
         key_name=mykey
    register: rax

  - name: add hosts to groups
    add_host: hostname={{ item.name }} groupname=only
              ansible_ssh_host={{ item.rax_accessipv4 }}
    with_items: rax.success
    when: rax.action == 'create'

  - name: wait for new servers to launch
    wait_for: host={{ item.rax_accessipv4 }} port=22 state=started
    with_items: rax.success
    when: rax.action == 'create'

- name: use it
  hosts: only
  remote_user: root
  tasks:

  - name: install git
    apt: pkg=git state=installed update_cache=true
