---
- name: provision
  hosts: local
  connection: local
  tasks:

  - name: provision the server
    rax: credentials=~/.rackspace_cloud_credentials name=foo
         exact_count=yes count=2 group=only
         image=ubuntu-1204-lts-precise-pangolin
         flavor=performance1-1
         region=IAD
         state=present
         wait=yes
         key_name=tiger
    register: rax

  - name: add hosts to groups
    add_host: hostname={{ item.name }} groupname=only
              ansible_ssh_host={{ item.rax_accessipv4 }}
    with_items: rax.success
    when: rax.action == 'create'

- name: use it
  hosts: only
  remote_user: root
  tasks:

  - name: install git
    apt: pkg=git state=installed update_cache=true
